# Generated by Django 6.0.5 on 2026-05-09 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('rok', models.IntegerField()),
                ('status', models.CharField(choices=[('dostępny', 'Dostępny'), ('naprawa', 'W naprawie'), ('zarezerwowany', 'Zarezerwowany')], default='dostępny', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('przebieg', models.IntegerField()),
                ('opis_naprawy', models.TextField()),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateTimeField()),
                ('data_koniec', models.DateTimeField()),
                ('użytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pojazd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle')),
            ],
        ),
    ]
